spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka