spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/authentication/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses,/api/v1/courses/**,/api/v1/reviews,/api/v1/reviews/**,/api/v1/materials,/api/v1/materials/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
