spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/authentication/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
